apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcharts.platformref.crossplane.io
spec:
  group: platformref.crossplane.io
  names:
    kind: XChart
    plural: xcharts
  claimNames:
    kind: Chart
    plural: charts
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: Name of the release instance
              version:
                type: string
                description: Chart version to run.
              clusterRef:
                type: string
                description: Cluster to deploy to


