apiVersion: azure.platformref.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-azure
spec:
  id: platform-ref-azure
  parameters:
    nodes:
      count: 1 #1-100
      size: small #small/medium/large
    charts:
      wordpress:
        version: "13.1.15"

