apiVersion: platformref.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-azure
spec:
  id: platform-ref-azure
  parameters:
    nodes:
      count: 1
      size: large
  cloud: azure
