apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xmariadbinstances.db.platformref.crossplane.io
  labels:
    cloud: azure
spec:
  compositeTypeRef:
    apiVersion: db.platformref.crossplane.io/v1alpha1
    kind: XSQLSrv
  resources:
  - base:
      apiVersion: dbformariadb.azure.jet.crossplane.io/v1alpha1
      kind: Server
      spec:
        forProvider:
          name: mariadb-server # patched
          version: "10.3"
          administratorLogin: myadmin
          location: East US 2
          sslEnforcement: Disabled
          storageMb: 5120 # patched
          skuName: "B_Gen5_2"
    name: mariadbserver
    patches:
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: metadata.name
      transforms:
        - type: string
          string:
            fmt: "%s-mariadb" 
    # - fromFieldPath: spec.parameters.clusterRef.id
    #   toFieldPath: spec.forProvider.name
    #   transforms:
    #     - type: string
    #       string:
    #         fmt: "%s-mariadb"
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: metadata.annotations[crossplane.io/external-name]
      transforms:
        - type: string
          string:
            fmt: "%s-mariadb"
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.writeConnectionSecretToRef.namespace
    - fromFieldPath: "spec.parameters.clusterRef.id"
      toFieldPath: "spec.writeConnectionSecretToRef.name"
      transforms:
      - type: string
        string:
          fmt: "%s-mariadb"
    - fromFieldPath: "spec.parameters.storageGB"
      toFieldPath: "spec.forProvider.storageMb"
      transforms:
      - type: math
        math:
          multiply: 1024
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: spec.forProvider.resourceGroupNameSelector.matchLabels[azure.platformref.crossplane.io/app]
    connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port
  # db-server vnet-rule for subnet where AKS lives in
  - name: vnetrule
    base:
      apiVersion: dbformariadb.azure.jet.crossplane.io/v1alpha1
      kind: VirtualNetworkRule
      spec:
        forProvider:
          name: mariadb #patched
          serverName: mariadb #patched
    patches:
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: "%s-sn"
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: spec.forProvider.serverName
      transforms:
        - type: string
          string:
            fmt: "%s-mariadb"
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: spec.forProvider.name
      transforms:
        - type: string
          string:
            fmt: "%s-sn-rule"
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: metadata.annotations[crossplane.io/external-name]
      transforms:
        - type: string
          string:
            fmt: "%s-sn-rule"
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: spec.forProvider.subnetIdSelector.matchLabels[azure.platformref.crossplane.io/app]
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: spec.forProvider.resourceGroupNameSelector.matchLabels[azure.platformref.crossplane.io/app]
